 name: mypy

 on: [push]

 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: ["3.11", "3.12", "3.13"]
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install mypy
       run: |
         python3 -m pip install --upgrade pip
         python3 -m pip install mypy
     - name: Analyzing the code with mypy
       run: |
         mypy .
